name: contactos_foundation
description: iOS implementation of the contactos plugin.
version: 0.0.4

# publish_to: none

homepage: https://github.com/ziqq/contactos

repository: https://github.com/ziqq/contactos/tree/main/contactos_foundation

issue_tracker: https://github.com/ziqq/contactos/issues

funding:
  - https://www.buymeacoffee.com/ziqq
  - https://boosty.to/ziqq

#screenshots:
#  - description: 'Example of using the library to check app version.'
#    path: example.png

topics:
  - contacts


environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.29.0"


dependencies:
  flutter:
    sdk: flutter

  contactos_platform_interface: ^1.0.2
  # contactos_platform_interface:
  #   path: ../contactos_platform_interface


dev_dependencies:
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ContactosPlugin
        dartPluginClass: ContactosPluginFoundation
        sharedDarwinSource: true
      # macos:
      #   pluginClass: ContactosPlugin
      #   dartPluginClass: ContactosPluginFoundation
      #   sharedDarwinSource: true

