plugins {
    id "com.android.library"
}

android {
    namespace  = 'flutter.plugins.contactos'
    compileSdk = flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk                    = flutter.minSdkVersion
        targetSdk                 = flutter.targetSdkVersion
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.12'
    testImplementation 'com.google.truth:truth:1.0'
}

flutter {
    source = "../.."
}