name: contactos_ios
description: iOS and macOS implementation of the contactos plugin.
repository: https://github.com/ziqq/contactos/contactos_ios
issue_tracker: https://github.com/ziqq/contactos/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+contactos%22
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.29.3"

flutter:
  plugin:
    implements: contactos
    platforms:
      ios:
        pluginClass: ContactosPlugin
        dartPluginClass: ContactosIos
      macos:
        pluginClass: ContactosPlugin
        dartPluginClass: ContactosIos

dependencies:
  flutter:
    sdk: flutter

  # contactos_platform_interface: ^1.0.0
  contactos_platform_interface:
    path: ../contactos_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^25.0.0

  # Linting
  flutter_lints: ^5.0.0

topics:
  - contacts
